# Generated by Django 5.1 on 2024-09-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_productocategoria_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productocategoria',
            old_name='decripcion',
            new_name='descripcion',
        ),
    ]
